### ISSUE TITLE
Wrong mime type detection

### ISSUE THREAD

**Issue by goraSi** [npcz/magic#1]
Hi there. I have been using this great library for a while now. With one file i got a difference using this library and LINUX file command:

> Magic:
`magic.detectMimeType(file)
output: application/csv`

>Linux file command
`file --mime-type file.csv
output: text/plain`

I'm using this function to detect extension of the file which in this case is undefined beacuse `application/csv` is not a valid mime type.

`magic.detect(file, magicFlags.MAGIC_EXTENSION) output: ???`

Any ideas why detection doesn't work as expected.

**Comment by abdes** [comment]
I just did a quick test on Mac OS X Darwin.

```
(base)[~/Projects/npcz/magic]$ yarn examples | grep file.csv                                                                       *[master]
file.csv  :  text/plain; charset=us-ascii
file.csv  :  ASCII text
file_csv  :  text/plain; charset=us-ascii
file_csv  :  ASCII text
file.csv  :  text/plain; charset=us-ascii
file.csv  :  ASCII text
file_csv  :  text/plain; charset=us-ascii
file_csv  :  ASCII text

(base)[~/Projects/npcz/magic]$ file file.csv                                                                                       *[master]
file.csv: ASCII text

(base)[~/Projects/npcz/magic]$ file file_csv                                                                                       *[master]
file_csv: ASCII text

(base)[~/Projects/npcz/magic]$ cat file_csv                                                                                        *[master]
aa,ssss,ddd,fff
www,eee,rr,rr

(base)[~/Projects/npcz/magic]$ cat file.csv                                                                                        *[master]
aa,ssss,ddd,fff
www,eee,rr,rr
```

The result of the detection is consistent with what OS X file command is returning. There maybe differences between the magic detection file embedded into @npcz/magic and the magic detection file you are having on your linux system. Could you please try to replace the .mgc file in node_modules with the same file you are using on Linux and retest?

**Comment by abdes** [comment]
I think I know why. Your CSV files is having too few lines maybe. I rerun the test with a file that has more lines and the detection came back as CSV:

```
file.csv  :  application/csv; charset=us-ascii
file.csv  :  CSV text
file_csv  :  application/csv; charset=us-ascii
file_csv  :  CSV text
```

Now the content of the files is:

```
1,aa,ssss,ddd,fff
2,a,ssss,ddd,fff
3,aa,ssss,ddd,fff
4,aa,ssss,ddd,fff
5,aa,ssss,ddd,fff
6,aa,ssss,ddd,fff
7,aa,ssss,ddd,fff
8,aa,ssss,ddd,fff
9,aa,ssss,ddd,fff
10,aa,ssss,ddd,fff
11,aa,ssss,ddd,fff
12aa,ssss,ddd,fff
13,www,eee,rr,rr
```

It also works with 3 lines or more.

It seems that the minimum required by libmagic is 3 lines.  

**UPDATE:**
Looking at the C code, I confirm, minimum is 3 lines:

```C
		}
	}
	return tf && nl > 2;
}
```

**Comment by goraSi** [comment]
My file has 4 lines. I will try to use another magic file and re-test.

**Comment by abdes** [comment]
Can you also make sure that your CSV file does actually use **comma** to separate records in a line?
For example, excel can accept CSV files with other separators such as ; or tab etc....
libmagic only detects **'comma'**.

I tested again on a windows system and if you call the file file.csv, but the content is tab-separated, excel will like it but libmagic will not detect CSV inside.

**Comment by goraSi** [comment]
CSV file has seperator ";". I have tried to copy magic file from linux to my win machine but i'm getting error:
`failed to initialize libmagic`

Any idea how can i use another magic file.

**Comment by abdes** [comment]
Only comma is supported by libmagic.

Please test with comma instead of semicolon

**Comment by goraSi** [comment]
I have added `application/csv` to my mime type db so this is solving my issue.
