### ISSUE TITLE
Using it with electron?

### ISSUE THREAD

**Issue by vanowm** [npcz/magic#9]
Any tutorial how to use it with Electron?

**Comment by abdes** [comment]
Here is an example that works both during development with Webpack serving files over http and in production where everything is served out of the filesystem. You may need to adjust based on your own environment.

```typescript
  // This method will be called when Electron has finished
  // initialization and is ready to create browser windows.
  // Some APIs can only be used after this event occurs.
  app.on('ready', () => {
    // Initialize the file magic wasm module

    // Init the FileMagic
    FileMagic.magicFile = path.join(__dirname, 'magic.mgc');
    // Customize the emscripten JS wrapper logic for loading the wasm file to accommodate 
    // for our two working modes: during development, we rely on webpack serving the files 
    // over http, while in production, we load from the file system.
    let locateFile = null;
    if (electronIsDev) {
      locateFile = function (wasmPath: string, scriptDirectory: string) {
        console.log(`locateFile(${wasmPath}, ${scriptDirectory})`);
        return 'http://localhost:4200/' + wasmPath;
      };
    }
    FileMagic.getInstance()
      .then((instance) => {
        magic = instance;
        initMainListener();
        createWorkers();
        createWindow();
      })
      .catch((err) => {
        log.error(err);
        log.info('File type detection will not be available.');
        initMainListener();
        createWorkers();
        createWindow();
      });
  });
```

`initMainListeners()`, `createWorkers()`,`createWindow()` are my init functions for the electron app... Of course, you need to use your own. code there.

**Comment by vanowm** [comment]
I'm confused about `locateFile` function, it's not used in this code...
Also, the installation tutorial installs `@npcz/magic` but  imports from `../lib/index` ?

**Comment by abdes** [comment]
`locateFile` is called by emscripten, behind the scenes, every time it needs to load a file and it allows us to have flexibility in where the files are located.

See [`Module.locateFile`](https://emscripten.org/docs/api_reference/module.html#Module.locateFile) in the emscripten docs.
